package org.walter.common.ui.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SConceptOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.Collections;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    {
      SAbstractConcept cncpt = ((SAbstractConcept) concept);
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, "org.walter.common.ui.structure.CheckBox"))) {
        return Collections.<ConceptEditor>singletonList(new CheckBox_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x622d6428b5f865feL, "org.walter.common.ui.structure.CheckBoxText"))) {
        return Collections.<ConceptEditor>singletonList(new CheckBoxText_Editor());
      }
      if (SConceptOperations.isExactly(SNodeOperations.asSConcept(cncpt), MetaAdapterFactory.getConcept(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x7bf6c30e4f52e957L, "org.walter.common.ui.structure.SelectedAttribute"))) {
        return Collections.<ConceptEditor>singletonList(new SelectedAttribute_Editor());
      }
    }
    return Collections.<ConceptEditor>emptyList();
  }



}
