package org.walter.common.ui.runtime.rtModel;

/*Generated by MPS */

import java.awt.Font;

public interface CheckBoxPropertiesProvider {
  public boolean getInitValue();
  public boolean getIsOpaque();
  public String getText();
  public int getHorizontalTextPosition();
  public Font getFont();
  public int getStyle();
}
