package org.walter.common.ui.runtime.rtModel;

/*Generated by MPS */

import java.util.ArrayList;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.openapi.editor.EditorContext;

public abstract class CheckBoxCallBack implements Runnable {
  /*package*/ ArrayList<String> paths;
  /*package*/ SNode checkboxContainer;
  /*package*/ EditorContext editorContext;
  public CheckBoxCallBack(SNode node, EditorContext editorContext) {
    this.editorContext = editorContext;
    this.checkboxContainer = node;
  }
  public abstract void process(SNode node, EditorContext editorContext);
  public void run() {
    process(this.checkboxContainer, this.editorContext);
  }
}
