package org.walter.common.ui.runtime.rtModel;

/*Generated by MPS */

import javax.swing.Icon;
import javax.swing.ImageIcon;

public class IconProvider {
  /*package*/ int style;
  public IconProvider(int style) {
    this.style = style;
  }
  public Icon getIcon() {
    switch (style) {
      case 1:
        return new ImageIcon(getClass().getResource("..\\..\\..\\..\\..\\..\\..\\resources\\Off2.png"), "");
      default:
        return null;
    }
  }

  public Icon getSelectedIcon() {
    switch (style) {
      case 1:
        return new ImageIcon(getClass().getResource("..\\..\\..\\..\\..\\..\\..\\resources\\On2.png"), "");
      default:
        return null;
    }
  }

}
