package org.walter.common.ui.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum CheckBoxTextFonts {
  Courier_New("Courier New", "Courier New"),
  Trebuchet_MS("Trebuchet MS", "Trebuchet MS"),
  Verdana("Verdana", "Verdana"),
  Arial("Arial", "Arial");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  CheckBoxTextFonts(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<CheckBoxTextFonts> getConstants() {
    List<CheckBoxTextFonts> list = ListSequence.fromList(new LinkedList<CheckBoxTextFonts>());
    ListSequence.fromList(list).addElement(CheckBoxTextFonts.Courier_New);
    ListSequence.fromList(list).addElement(CheckBoxTextFonts.Trebuchet_MS);
    ListSequence.fromList(list).addElement(CheckBoxTextFonts.Verdana);
    ListSequence.fromList(list).addElement(CheckBoxTextFonts.Arial);
    return list;
  }
  public static CheckBoxTextFonts getDefault() {
    return CheckBoxTextFonts.Courier_New;
  }
  public static CheckBoxTextFonts parseValue(String value) {
    if (value == null) {
      return CheckBoxTextFonts.getDefault();
    }
    if (value.equals(CheckBoxTextFonts.Courier_New.getValueAsString())) {
      return CheckBoxTextFonts.Courier_New;
    }
    if (value.equals(CheckBoxTextFonts.Trebuchet_MS.getValueAsString())) {
      return CheckBoxTextFonts.Trebuchet_MS;
    }
    if (value.equals(CheckBoxTextFonts.Verdana.getValueAsString())) {
      return CheckBoxTextFonts.Verdana;
    }
    if (value.equals(CheckBoxTextFonts.Arial.getValueAsString())) {
      return CheckBoxTextFonts.Arial;
    }
    return CheckBoxTextFonts.getDefault();
  }
}
