package org.walter.common.ui.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum HorizPos {
  _4("RIGHT", 4),
  _2("LEFT", 2);

  private final String myName;
  public String getName() {
    return myName;
  }
  private final int myValue;
  HorizPos(String name, int value) {
    myName = name;
    myValue = value;
  }
  public int getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return Integer.toString(myValue);
  }
  public static List<HorizPos> getConstants() {
    List<HorizPos> list = ListSequence.fromList(new LinkedList<HorizPos>());
    ListSequence.fromList(list).addElement(HorizPos._4);
    ListSequence.fromList(list).addElement(HorizPos._2);
    return list;
  }
  public static HorizPos getDefault() {
    return HorizPos._4;
  }
  public static HorizPos parseValue(String value) {
    if (value == null) {
      return HorizPos.getDefault();
    }
    if (value.equals(HorizPos._4.getValueAsString())) {
      return HorizPos._4;
    }
    if (value.equals(HorizPos._2.getValueAsString())) {
      return HorizPos._2;
    }
    return HorizPos.getDefault();
  }
}
