package org.walter.common.ui.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {

  /*package*/ final ConceptDescriptor myConceptCheckBox = new ConceptDescriptorBuilder("org.walter.common.ui.structure.CheckBox", MetaIdFactory.conceptId(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L)).super_("jetbrains.mps.lang.editor.structure.EditorCellModel").super_(MetaIdFactory.conceptId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xf9eafb9a39L)).parents("jetbrains.mps.lang.editor.structure.EditorCellModel").parentIds(MetaIdFactory.conceptId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0xf9eafb9a39L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(4543953829994930599L, "identifier"), new ConceptDescriptorBuilder.Prop(58006556489828164L, "opaque"), new ConceptDescriptorBuilder.Prop(3999703203729181085L, "style")).properties("identifier", "opaque", "style").childDescriptors(new ConceptDescriptorBuilder.Link(4543953829994930608L, "onSelected", MetaIdFactory.conceptId(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa1a9L), false, false, false), new ConceptDescriptorBuilder.Link(4543953829994930610L, "onDeSelected", MetaIdFactory.conceptId(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa1afL), false, false, false), new ConceptDescriptorBuilder.Link(4601216887035799527L, "initValueCondition", MetaIdFactory.conceptId(0x18bc659203a64e29L, 0xa83a7ff23bde13baL, 0x10a1953c797L), false, false, false), new ConceptDescriptorBuilder.Link(7074420715683348413L, "checkBoxText", MetaIdFactory.conceptId(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x622d6428b5f865feL), true, false, false)).children(new String[]{"onSelected", "onDeSelected", "initValueCondition", "checkBoxText"}, new boolean[]{false, false, false, false}).alias("checkbox", "swing CheckBox").create();
  /*package*/ final ConceptDescriptor myConceptCheckBoxText = new ConceptDescriptorBuilder("org.walter.common.ui.structure.CheckBoxText", MetaIdFactory.conceptId(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x622d6428b5f865feL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(7074420715683341823L, "text"), new ConceptDescriptorBuilder.Prop(7074420715683341826L, "horizPos"), new ConceptDescriptorBuilder.Prop(143045343736973052L, "font")).properties("text", "horizPos", "font").create();
  /*package*/ final ConceptDescriptor myConceptOnDeSelected = new ConceptDescriptorBuilder("org.walter.common.ui.structure.OnDeSelected", MetaIdFactory.conceptId(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa1afL)).super_("jetbrains.mps.baseLanguage.structure.ConceptFunction").super_(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L)).parents("jetbrains.mps.baseLanguage.structure.ConceptFunction").parentIds(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L)).alias("on de-selection", "run when checkbox is de-selected").create();
  /*package*/ final ConceptDescriptor myConceptOnSelected = new ConceptDescriptorBuilder("org.walter.common.ui.structure.OnSelected", MetaIdFactory.conceptId(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa1a9L)).super_("jetbrains.mps.baseLanguage.structure.ConceptFunction").super_(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L)).parents("jetbrains.mps.baseLanguage.structure.ConceptFunction").parentIds(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L)).alias("on selection", "run when checkbox is selected").create();
  /*package*/ final ConceptDescriptor myConceptSelectedAttribute = new ConceptDescriptorBuilder("org.walter.common.ui.structure.SelectedAttribute", MetaIdFactory.conceptId(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x7bf6c30e4f52e957L)).super_("jetbrains.mps.lang.core.structure.NodeAttribute").super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da54L)).parents("jetbrains.mps.lang.core.structure.NodeAttribute").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x2eb1ad060897da54L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(8932541377163749773L, "id")).properties("id").create();

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCheckBox, myConceptCheckBoxText, myConceptOnDeSelected, myConceptOnSelected, myConceptSelectedAttribute);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(String conceptFqName) {
    switch (Arrays.binarySearch(stringSwitchCases_1htk8d_a0a0j, conceptFqName)) {
      case 0:
        return myConceptCheckBox;
      case 1:
        return myConceptCheckBoxText;
      case 2:
        return myConceptOnDeSelected;
      case 3:
        return myConceptOnSelected;
      case 4:
        return myConceptSelectedAttribute;
      default:
        return null;
    }
  }
  private static String[] stringSwitchCases_1htk8d_a0a0j = new String[]{"org.walter.common.ui.structure.CheckBox", "org.walter.common.ui.structure.CheckBoxText", "org.walter.common.ui.structure.OnDeSelected", "org.walter.common.ui.structure.OnSelected", "org.walter.common.ui.structure.SelectedAttribute"};
}
