package org.walter.common.ui.generator.template.main;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;

@Generated
public class QueriesGenerated {
  public static Object propertyMacro_GetPropertyValue_58006556490005892(final PropertyMacroContext _context) {
    return SPropertyOperations.getBoolean(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, "org.walter.common.ui.structure.CheckBox")), MetaAdapterFactory.getProperty(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, 0xce14a7e2384744L, "opaque"));
  }
  public static Object propertyMacro_GetPropertyValue_7074420715683401363(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, "org.walter.common.ui.structure.CheckBox")), MetaAdapterFactory.getContainmentLink(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, 0x622d6428b5f87fbdL, "checkBoxText")), MetaAdapterFactory.getProperty(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x622d6428b5f865feL, 0x622d6428b5f865ffL, "text"));
  }
  public static Object propertyMacro_GetPropertyValue_7074420715683409020(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger_def(SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, "org.walter.common.ui.structure.CheckBox")), MetaAdapterFactory.getContainmentLink(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, 0x622d6428b5f87fbdL, "checkBoxText")), MetaAdapterFactory.getProperty(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x622d6428b5f865feL, 0x622d6428b5f86602L, "horizPos"), "4");
  }
  public static Object propertyMacro_GetPropertyValue_143045343737023242(final PropertyMacroContext _context) {
    return SPropertyOperations.getString_def(SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, "org.walter.common.ui.structure.CheckBox")), MetaAdapterFactory.getContainmentLink(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, 0x622d6428b5f87fbdL, "checkBoxText")), MetaAdapterFactory.getProperty(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x622d6428b5f865feL, 0x1fc32fb743746fcL, "font"), "Courier New");
  }
  public static Object propertyMacro_GetPropertyValue_3999703203729261633(final PropertyMacroContext _context) {
    return SPropertyOperations.getInteger_def(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, "org.walter.common.ui.structure.CheckBox")), MetaAdapterFactory.getProperty(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, 0x3781ccdf5945099dL, "style"), "0");
  }
  public static Object propertyMacro_GetPropertyValue_8932541377163669803(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, "org.walter.common.ui.structure.CheckBox")), MetaAdapterFactory.getProperty(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, 0x3f0f5deef89fa1a7L, "identifier"));
  }
  public static Iterable<SNode> sourceNodesQuery_8932541377163603230(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, "org.walter.common.ui.structure.CheckBox")), MetaAdapterFactory.getContainmentLink(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, 0x3f0f5deef89fa1b0L, "onSelected")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L, 0x108bbd29b4aL, "body")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"));
  }
  public static Iterable<SNode> sourceNodesQuery_8932541377163637787(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, "org.walter.common.ui.structure.CheckBox")), MetaAdapterFactory.getContainmentLink(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, 0x3f0f5deef89fa1b2L, "onDeSelected")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L, 0x108bbd29b4aL, "body")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"));
  }
  public static Iterable<SNode> sourceNodesQuery_58006556489962033(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(SLinkOperations.getTarget(SLinkOperations.getTarget(SNodeOperations.cast(_context.getNode(), MetaAdapterFactory.getConcept(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, "org.walter.common.ui.structure.CheckBox")), MetaAdapterFactory.getContainmentLink(0x949fc8316aef4545L, 0x8859ffa2eed47cbfL, 0x3f0f5deef89fa172L, 0x3fdace61664c27e7L, "initValueCondition")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0x108bbca0f48L, 0x108bbd29b4aL, "body")), MetaAdapterFactory.getContainmentLink(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8cc56b200L, 0xf8cc6bf961L, "statement"));
  }
}
